export const people = [
    {
        id: 1,
        name:'First LastName',
        age:27,
        birthday: '',
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 2,
        name:'First LastName',
        age:28,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 3,
        name:'First LastName',
        age:29,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 4,
        name:'First LastName',
        age:30,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 5,
        name:'First LastName',
        age:31,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 6,
        name:'First LastName',
        age:32,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 7,
        name:'First LastName',
        age:33,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
    {
        id: 8,
        name:'First LastName',
        age:34,
        birthday: '',
        pic:'./styles/person1.jpg',
    },
]